apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-service
  description: Core microservice that handles billing logic and account charges.
  tags:
    - backend
    - payments
  links:
    - url: https://github.com/theorganizationtfg/theorg-catalog
      title: GitHub Catalog
      icon: github
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: app=backstage-backend
    backstage.io/kubernetes-namespace: backstage
    argocd/app-name: backstage
    jenkins.io/job-full-name: backstage-k3s-docker-pipeline
    github.com/project-slug:  theorganizationtfg/theorg-catalog
    backstage.io/adr-location: adrs
    jira/project-key: SCRUM
    prometheus.io/rule: sum by (instance) (node_cpu_seconds_total), node_memory_MemAvailable_bytes|instance
spec:
  type: service
  lifecycle: production
  owner: group:default/chapter-backend
  system: billing-system
