apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  annotations:
    backstage.io/kubernetes-id: backstage-backend
    argocd/app-name: backstage
    jenkins.io/job-full-name: backstage-k3s-docker-pipeline
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
