apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: REST API for managing user authentication and issuing tokens.
  tags:
    - auth
    - api
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: production
  owner: group:default/chapter-backend
  system: authentication-system
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml
