apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: REST API for managing user authentication and issuing tokens.
  tags:
    - auth
    - api
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  lifecycle: production
  owner: group:default/chapter-backend
  system: authentication-system
