name: Create Deployment on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_deployment:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Deployment
        id: deployment
        uses: chrnorm/deployment-action@v2.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: prod
          ref: ${{ github.ref_name }}
