name: Create Deployment on Push

on:
  push:
    branches:
      - main

jobs:
  create_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Deployment
        id: deployment
        uses: actions/create-deployment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: prod
          ref: ${{ github.ref_name }}
          transient_environment: false
          production_environment: false

      - name: Set Deployment Status to “success”
        uses: actions/create-deployment-status@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          state: success
